// generated by stringer -type=errorCode; DO NOT EDIT

package tftp

import "fmt"

const _errorCode_name = "FileNotFoundAccessViolationDiskFullIllegalOperationUnknownTransferIDFileAlreadyExistsNoSuchUsermaxErrorCode"

var _errorCode_index = [...]uint8{0, 12, 27, 35, 51, 68, 85, 95, 107}

func (i errorCode) String() string {
	i -= 1
	if i >= errorCode(len(_errorCode_index)-1) {
		return fmt.Sprintf("errorCode(%d)", i+1)
	}
	return _errorCode_name[_errorCode_index[i]:_errorCode_index[i+1]]
}
