// generated by stringer -type=Mode; DO NOT EDIT

package tftp

import "fmt"

const _Mode_name = "OctetNetasciiMailmaxMode"

var _Mode_index = [...]uint8{0, 5, 13, 17, 24}

func (i Mode) String() string {
	i -= 1
	if i >= Mode(len(_Mode_index)-1) {
		return fmt.Sprintf("Mode(%d)", i+1)
	}
	return _Mode_name[_Mode_index[i]:_Mode_index[i+1]]
}
