// generated by stringer -type=opcode; DO NOT EDIT

package tftp

import "fmt"

const _opcode_name = "RRQWRQDATAACKERROROACKmaxopcode"

var _opcode_index = [...]uint8{0, 3, 6, 10, 13, 18, 22, 31}

func (i opcode) String() string {
	i -= 1
	if i >= opcode(len(_opcode_index)-1) {
		return fmt.Sprintf("opcode(%d)", i+1)
	}
	return _opcode_name[_opcode_index[i]:_opcode_index[i+1]]
}
