// generated by stringer -type=option; DO NOT EDIT

package tftp

import "fmt"

const _option_name = "blksizetimeouttsizemulticastwindowsizemaxOption"

var _option_index = [...]uint8{0, 7, 14, 19, 28, 38, 47}

func (i option) String() string {
	i -= 1
	if i >= option(len(_option_index)-1) {
		return fmt.Sprintf("option(%d)", i+1)
	}
	return _option_name[_option_index[i]:_option_index[i+1]]
}
